name: Create Docker Image Mock

on:
  workflow_call:
    secrets:
      CI4_DOCKERHUB_USERNAME:
        required: true
      CI4_DOCKERHUB_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Name to tag the image with'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
    - name: Print event name
      run: echo "${{ github.event_name }}"

    - name: Build and push Release Docker Image
      if: ${{ github.event_name == 'workflow_call' }}
      run: echo "Would call docker build and push"
